### ISSUE TITLE
StoryboardLint should use latest version of nokogiri; avoids problem with libxml2 on Mavericks

### ISSUE THREAD

**Issue by fatuhoku** [jfahrenkrug/StoryboardLint#11]
I updated to Mavericks from Mountain Lion yesterday night. There were some teething issues when trying to run my project ( :( ). More specifically I ran into [this problem with libxml2](http://stackoverflow.com/questions/15842346/getting-nokogiri-to-use-a-newer-version-of-libxml2).

The only way around the problem is to install the latest version of `nokogiri` with a special command using Homebrew, which at the time of writing is `nokogiri-1.6.2.1`.

Sadly, this version cannot be used by StoryboardLint because it depends on `nokogiri-1.5.x`.

I know it's not a problem with StoryboardLint, but please update, or provide instructions for a workaround. For now, I haven't found a way and will disable StoryboardLint until the issue is fixed.

**Comment by jfahrenkrug** [comment]
Closing this for now
